# Application configuration file

spring.application.name=spring-learn-jwt

# The authentication service runs on port 8090
server.port=8090

logging.level.root=INFO
logging.level.com.cognizant.springlearn=DEBUG
