# Application configuration file

spring.application.name=spring-learn-country

# The assignment uses http://localhost:8083/country
server.port=8083

logging.level.root=INFO
logging.level.com.cognizant.springlearn=DEBUG
